# taken from https://www.google.com/search?q=mad+lib&client=firefox-b-d&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi_kKypiYnlAhXvYt8KHS8HAUMQ_AUIESgB&biw=628&bih=742#imgrc=N5In1AI-UalC0M:
name = input("Please choose a name")
sillyWord = input("Please choose a silly word")
number = input("Please pick a number")
adjective1 = input("Please pick an adjective")
noun = input("Please pick a noun")
adjective2 = input("Please pick another adjective")
relative = input("Pick a type of relative")
adjective3 = input("Please pick another adjective")
verb = input("Please pick a verb")
adjective4 = input("Please pick another adjective")
adjective5 = input("Please pick another adjective")

print("\nSpace Exploration MadLib\n")
print("Hello, my name is astronaut " + name + ". I am on my way to planet " + sillyWord + ".")
print("I will be gone for " + number + " days. I am very " + adjective1 + " about the trip but I")
print("will miss my " + noun + ". I have heard that the atmosphere there is " + adjective2 + ".")
print("Luckily my " + relative + " packed me a jacket to keep me " + adjective3 + ".")
print("When I land on the planet I will " + verb + " for joy. I am " + adjective4 + " to walk on")
print("another planet. I could not be more " + adjective5 + " for this trip!")